# nelmio_cors:
#     defaults:
#         # origin_regex: true
#         allow_origin: ['*']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/api/':   
#             allow_origin: ['http://localhost:3000']
#             allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
#             allow_headers: ['Content-Type', 'Authorization']
#             expose_headers: ['Link']


# nelmio_cors:
#     defaults:
#         allow_origin: ['http://localhost:5173'] # Adresse du serveur Vite
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/api/':
#             allow_origin: ['http://localhost:5173']


nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5174']  # Remplacez par l'URL de votre frontend
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':  # Applique cette configuration uniquement aux routes commençant par /api/
            allow_origin: ['*']  # Vous pouvez restreindre cela à une origine spécifique
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
